version: '3.8'

services:
  headscale:
    build:
      context: ./headscale
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: headscale
    tmpfs:
      - /var/run/headscale
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - headscale_data:/var/lib/headscale
    command: serve -c /etc/headscale/config.yaml
    healthcheck:
      test: ["CMD", "headscale", "health"]

  headplane:
    build:
      context: ./headplane
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: headplane
    ports:
      - "3000:3000"
    volumes:
      - headplane_data:/var/lib/headplane
    environment:
      - COOKIE_SECRET=${COOKIE_SECRET}
      - HEADPLANE_LOAD_ENV_OVERRIDES=true
      - HEADPLANE_HEADSCALE__URL=http://headscale:8080
      # You MUST generate an API key on Headscale and update this value in the Railway Dashboard:
      - HEADPLANE_HEADSCALE__API_KEY=${HEADPLANE_API_KEY:-replace_me_after_deployment}

volumes:
  headscale_data:
  headplane_data:
